const EMAIL_TEMPLATES = {
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    SIGN_UP: 'SIGN_UP',
    REGISTER: 'REGISTER',
    RESEND_OTP: 'RESEND_OTP',
    WELCOME: 'WELCOME',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    INVITE: 'INVITE',
    USER_ACTIVITY: 'USER_ACTIVITY',
    EXCEPTION: 'EXCEPTION',
    EVENT_UPDATE: 'EVENT_UPDATE',
    EVENT_CANCEL: 'EVENT_CANCEL',
    ORDER_BOOKED: 'ORDER_BOOKED',
    ORDER_CANCEL: 'ORDER_CANCEL',
};

module.exports = { EMAIL_TEMPLATES };
