name: Deploy to EC2

on:
  push:
    branches: [ Empire-Infratech ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Deploy via SSH
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ${{ secrets.EC2_APP_DIR }}

          # Delete local branch if it exists
          if git rev-parse --verify Empire-Infratech >/dev/null 2>&1; then
            git branch -D Empire-Infratech || true
          fi

          # Fetch and checkout the latest from origin
          git fetch origin Empire-Infratech
          git checkout -b Empire-Infratech origin/Empire-Infratech

          npm install
          pm2 restart all
        EOF
